### ISSUE TITLE
华为手机鸿蒙系统下，代码块里代码字体是衬线字体，但是电脑上是无衬线的 Consolas 字体

### ISSUE THREAD

**Issue by chuxinyuan** [yihui/yihui.org#1575]
如题。

https://github.com/yihui/yihui.org/blob/5dd472a6b575614841ae5ea176d5f7e490d15471/static/css/fonts.css#L19-L21

代码字体无衬线字体更舒服点，建议上面的代码改为如下代码：

```css
code {
  font-family: Consolas, 'Lucida Console', FandolKai, monospace;
}
```

另外，博客里的 “Github” 能否统一替换为 “GitHub”,我看了下大多数时候用的 “Github“，有时候用 “GitHub”。
