### ISSUE TITLE
Large whitespace after quotes

### ISSUE THREAD

**Issue by amarz45** [yihui/yihui.org#203]
On your website, there is a large amount of whitespace after ending single and double quotes (`’`, `”`). I think this is a problem with the font you chose, as when I override it, the problem is gone:

```css
body {
	font-family: Latin Modern Roman !important;
}
```
