### ISSUE TITLE
Add a toc for the tinytex faq

### ISSUE THREAD

**Issue by cderv** [yihui/yihui.org#95]
So that navigation is a lot easier ! 
https://yihui.org/tinytex/faq/

**Comment by cderv** [comment]
and related to #94

**Comment by yihui** [comment]
I agree, and I also wanted a TOC for this page for long. To do that, we need to move questions to headers (perhaps h2 or h3). Then we also need to number them, e.g., via CSS

```css
<style type="text/css">
body { counter-reset: faq; }
h2::before { counter-increment: faq; content: counter(faq) ". "; }
</style>
```
